# Generated by Django 4.1.7 on 2023-02-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vitrola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=60)),
                ('titulo', models.CharField(max_length=100)),
                ('track', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
