# Generated by Django 4.1.7 on 2023-02-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=60)),
                ('titulo', models.CharField(max_length=100)),
                ('track', models.FileField(upload_to='documents/')),
                ('nombre', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
