# Generated by Django 4.1.7 on 2023-02-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_waitlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitList',
        ),
    ]
